//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public string MaCTHD { get; set; }
        public string MaHD { get; set; }
        public string MaDV { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
