//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_SU_SUCO
    {
        public int ID { get; set; }
        public string MaSC { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SUCO SUCO { get; set; }
    }
}
