//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_SU_CANHO
    {
        public int MaLichSu { get; set; }
        public string MaCD { get; set; }
        public string MaCanHoCu { get; set; }
        public string MaCanHoMoi { get; set; }
        public string MaHDongCu { get; set; }
        public string MaHDongMoi { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CU_DAN CU_DAN { get; set; }
    }
}
