//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_O
    {
        public string MaNguoiO { get; set; }
        public string MaCanHo { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QuanHe { get; set; }
        public string CCCD { get; set; }
    
        public virtual CANHO CANHO { get; set; }
    }
}
