//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_CHUNGCUEntities : DbContext
    {
        public QL_CHUNGCUEntities()
            : base("name=QL_CHUNGCUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANHO> CANHOes { get; set; }
        public virtual DbSet<CT_HOADON> CT_HOADON { get; set; }
        public virtual DbSet<CU_DAN> CU_DAN { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOPDONG> HOPDONGs { get; set; }
        public virtual DbSet<LICH_SU_CANHO> LICH_SU_CANHO { get; set; }
        public virtual DbSet<LICH_SU_SUCO> LICH_SU_SUCO { get; set; }
        public virtual DbSet<NGUOI_O> NGUOI_O { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SU_DUNG_DV> SU_DUNG_DV { get; set; }
        public virtual DbSet<SUCO> SUCOes { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<THANH_TOAN> THANH_TOAN { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    
        public virtual int crs_KiemTraTheXeHetHan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crs_KiemTraTheXeHetHan");
        }
    
        public virtual int sp_CapNhatTrangThaiHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTrangThaiHoaDon");
        }
    
        public virtual int sp_ChuyenCanHo(string maCD, string maCanHoMoi, string loaiHopDongMoi, Nullable<decimal> giaTriHopDongMoi, string ghiChu)
        {
            var maCDParameter = maCD != null ?
                new ObjectParameter("MaCD", maCD) :
                new ObjectParameter("MaCD", typeof(string));
    
            var maCanHoMoiParameter = maCanHoMoi != null ?
                new ObjectParameter("MaCanHoMoi", maCanHoMoi) :
                new ObjectParameter("MaCanHoMoi", typeof(string));
    
            var loaiHopDongMoiParameter = loaiHopDongMoi != null ?
                new ObjectParameter("LoaiHopDongMoi", loaiHopDongMoi) :
                new ObjectParameter("LoaiHopDongMoi", typeof(string));
    
            var giaTriHopDongMoiParameter = giaTriHopDongMoi.HasValue ?
                new ObjectParameter("GiaTriHopDongMoi", giaTriHopDongMoi) :
                new ObjectParameter("GiaTriHopDongMoi", typeof(decimal));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenCanHo", maCDParameter, maCanHoMoiParameter, loaiHopDongMoiParameter, giaTriHopDongMoiParameter, ghiChuParameter);
        }
    
        public virtual int sp_GhiNhanSuCo(string maCanHo, string moTa)
        {
            var maCanHoParameter = maCanHo != null ?
                new ObjectParameter("MaCanHo", maCanHo) :
                new ObjectParameter("MaCanHo", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GhiNhanSuCo", maCanHoParameter, moTaParameter);
        }
    
        public virtual int sp_TangGiaTriHopDongBangCursor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TangGiaTriHopDongBangCursor");
        }
    
        public virtual ObjectResult<sp_TaoHoaDonMoi_Result> sp_TaoHoaDonMoi(string maHD, string maHDong, Nullable<System.DateTime> ngayLap, string thang)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maHDongParameter = maHDong != null ?
                new ObjectParameter("MaHDong", maHDong) :
                new ObjectParameter("MaHDong", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var thangParameter = thang != null ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TaoHoaDonMoi_Result>("sp_TaoHoaDonMoi", maHDParameter, maHDongParameter, ngayLapParameter, thangParameter);
        }
    
        public virtual int sp_ThemCuDanVaoCanHo(string maCD, string hoTen, Nullable<System.DateTime> ngaySinh, string gioiTinh, string sDT, string cCCD, string email, string maCanHo, string loaiHopDong, Nullable<decimal> giaTriHopDong)
        {
            var maCDParameter = maCD != null ?
                new ObjectParameter("MaCD", maCD) :
                new ObjectParameter("MaCD", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var maCanHoParameter = maCanHo != null ?
                new ObjectParameter("MaCanHo", maCanHo) :
                new ObjectParameter("MaCanHo", typeof(string));
    
            var loaiHopDongParameter = loaiHopDong != null ?
                new ObjectParameter("LoaiHopDong", loaiHopDong) :
                new ObjectParameter("LoaiHopDong", typeof(string));
    
            var giaTriHopDongParameter = giaTriHopDong.HasValue ?
                new ObjectParameter("GiaTriHopDong", giaTriHopDong) :
                new ObjectParameter("GiaTriHopDong", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCuDanVaoCanHo", maCDParameter, hoTenParameter, ngaySinhParameter, gioiTinhParameter, sDTParameter, cCCDParameter, emailParameter, maCanHoParameter, loaiHopDongParameter, giaTriHopDongParameter);
        }
    }
}
