//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class SU_DUNG_DV
    {
        public string MaSDDV { get; set; }
        public string MaCanHo { get; set; }
        public string MaDV { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public string ThangSuDung { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual CANHO CANHO { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
