//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCO()
        {
            this.LICH_SU_SUCO = new HashSet<LICH_SU_SUCO>();
        }
    
        public string MaSC { get; set; }
        public string MaCanHo { get; set; }
        public string MaNV { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CANHO CANHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_SU_SUCO> LICH_SU_SUCO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
