//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCO
    {
        public string MaSC { get; set; }
        public string MaCanHo { get; set; }
        public string MaNV { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayBao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CANHO CANHO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
