//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_TOAN
    {
        public string MaTT { get; set; }
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string HinhThuc { get; set; }
        public string NguoiThu { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
