//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_CHUNGCU
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        public string MaXe { get; set; }
        public string MaCanHo { get; set; }
        public string BienSo { get; set; }
        public string LoaiXe { get; set; }
        public string MauSac { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual CANHO CANHO { get; set; }
    }
}
